#!/usr/bin/env python3
# Generated by Claude Code
"""Quick test script for validating core functionality."""

import sys
sys.path.insert(0, 'claude-plugins/jira/skills/upload-slack-thread/scripts')

from url_parser import parse_slack_url, InvalidURLError
from ticket_extractor import extract_ticket_from_text, JIRATicketKey

def test_url_parsing():
    """Test URL parsing functionality."""
    print("Testing URL parsing...")

    # Valid URL
    url = "https://redhat-internal.slack.com/archives/C09Q8MD1V0Q/p1769333522823869"
    try:
        parsed = parse_slack_url(url)
        print(f"✓ Valid URL parsed successfully:")
        print(f"  Workspace: {parsed.workspace}")
        print(f"  Channel ID: {parsed.channel_id}")
        print(f"  Thread TS: {parsed.thread_ts}")
    except InvalidURLError as e:
        print(f"✗ Failed to parse valid URL: {e}")

    # Invalid URL
    print("\nTesting invalid URL...")
    try:
        parse_slack_url("https://invalid.com/not-a-slack-url")
        print("✗ Should have raised InvalidURLError")
    except InvalidURLError:
        print("✓ Invalid URL correctly rejected")

def test_ticket_extraction():
    """Test ticket extraction functionality."""
    print("\n\nTesting ticket extraction...")

    # Text with ticket
    text = "Let's discuss JN-1234 implementation details"
    ticket = extract_ticket_from_text(text)
    if ticket:
        print(f"✓ Found ticket: {ticket.raw_key}")
        print(f"  Project: {ticket.project}")
        print(f"  Number: {ticket.number}")
    else:
        print("✗ Failed to find ticket in text")

    # Text without ticket
    text_no_ticket = "Just a regular message"
    ticket = extract_ticket_from_text(text_no_ticket)
    if ticket is None:
        print("✓ Correctly returned None for text without ticket")
    else:
        print(f"✗ Should not have found ticket, but got: {ticket.raw_key}")

    # Test invalid format
    print("\nTesting invalid ticket format...")
    try:
        JIRATicketKey(raw_key="jn-1234")  # lowercase
        print("✗ Should have raised InvalidTicketKeyError")
    except Exception as e:
        print(f"✓ Invalid format correctly rejected: {type(e).__name__}")

if __name__ == "__main__":
    test_url_parsing()
    test_ticket_extraction()
    print("\n✓ All quick tests completed!")
