# Generated by Claude Code
"""
Contract tests for upload_slack_thread.py CLI interface.

These tests verify the CLI behaves according to contracts/cli-interface.md:
- Argument validation
- Exit codes
- Output streams (stdout/stderr)
"""

import subprocess
import sys
from pathlib import Path

import pytest

# Path to the main script
SCRIPT_PATH = Path(__file__).parent.parent.parent / "claude-plugins" / "jira" / "skills" / "upload-slack-thread" / "scripts" / "upload_slack_thread.py"

# Exit codes from cli-interface.md
EXIT_SUCCESS = 0
EXIT_INVALID_ARGS = 1
EXIT_SLACK_ERROR = 2
EXIT_JIRA_ERROR = 3
EXIT_AUTH_ERROR = 4
EXIT_NOT_FOUND = 5


def run_script(args: list[str], env: dict | None = None) -> subprocess.CompletedProcess:
    """
    Run the upload_slack_thread script with given arguments.

    Args:
        args: Command-line arguments
        env: Environment variables (merged with current env)

    Returns:
        CompletedProcess with returncode, stdout, stderr
    """
    import os
    full_env = os.environ.copy()
    if env:
        full_env.update(env)

    cmd = [sys.executable, str(SCRIPT_PATH)] + args
    return subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        env=full_env
    )


class TestCLIArguments:
    """Test CLI argument parsing and validation."""

    def test_missing_required_argument_shows_help(self):
        """Verify script requires slack_thread_url argument."""
        result = run_script([])
        assert result.returncode == 2  # argparse default error code
        assert "slack_thread_url" in result.stderr.lower()

    def test_help_flag_displays_usage(self):
        """Verify --help flag displays usage information."""
        result = run_script(["--help"])
        assert result.returncode == 0
        assert "slack_thread_url" in result.stdout.lower()
        assert "ticket_key" in result.stdout.lower()
        assert "--summary" in result.stdout.lower()
        assert "--verbose" in result.stdout.lower()

    def test_summary_flag_short_form(self):
        """Verify -s flag is accepted."""
        result = run_script([
            "https://workspace.slack.com/archives/C123/p456",
            "JN-1234",
            "-s"
        ], env={"JIRA_PROJECT_URL": "https://test.atlassian.net/", "JIRA_API_TOKEN": "test"})
        # Should not fail on argument parsing
        assert "unrecognized arguments" not in result.stderr.lower()

    def test_verbose_flag_short_form(self):
        """Verify -v flag is accepted."""
        result = run_script([
            "https://workspace.slack.com/archives/C123/p456",
            "JN-1234",
            "-v"
        ], env={"JIRA_PROJECT_URL": "https://test.atlassian.net/", "JIRA_API_TOKEN": "test"})
        # Should not fail on argument parsing
        assert "unrecognized arguments" not in result.stderr.lower()


class TestExitCodes:
    """Test exit codes per cli-interface.md contract."""

    def test_missing_jira_url_env_exits_with_invalid_args(self):
        """Verify missing JIRA_PROJECT_URL exits with EXIT_INVALID_ARGS."""
        result = run_script([
            "https://workspace.slack.com/archives/C123/p456",
            "JN-1234"
        ], env={"JIRA_API_TOKEN": "test", "JIRA_PROJECT_URL": ""})
        assert result.returncode == EXIT_INVALID_ARGS
        assert "JIRA_PROJECT_URL" in result.stderr

    def test_missing_jira_token_env_exits_with_auth_error(self):
        """Verify missing JIRA_API_TOKEN exits with EXIT_AUTH_ERROR."""
        result = run_script([
            "https://workspace.slack.com/archives/C123/p456",
            "JN-1234"
        ], env={"JIRA_PROJECT_URL": "https://test.atlassian.net/", "JIRA_API_TOKEN": ""})
        assert result.returncode == EXIT_AUTH_ERROR
        assert "JIRA_API_TOKEN" in result.stderr


class TestOutputStreams:
    """Test stdout/stderr separation per cli-interface.md."""

    def test_verbose_output_goes_to_stderr(self):
        """Verify verbose logs go to stderr, not stdout."""
        result = run_script([
            "https://workspace.slack.com/archives/C123/p456",
            "JN-1234",
            "--verbose"
        ], env={"JIRA_PROJECT_URL": "https://test.atlassian.net/", "JIRA_API_TOKEN": "test"})
        # Verbose/debug output should be in stderr
        assert "[DEBUG]" in result.stderr or "debug" in result.stderr.lower()

    def test_errors_go_to_stderr(self):
        """Verify errors are written to stderr."""
        result = run_script([
            "https://workspace.slack.com/archives/C123/p456",
            "JN-1234"
        ], env={"JIRA_PROJECT_URL": "", "JIRA_API_TOKEN": "test"})
        # Error about missing JIRA_PROJECT_URL should be in stderr
        assert result.stderr
        assert "ERROR" in result.stderr or "error" in result.stderr.lower()
