# Generated by Claude Code
"""
JIRA comment posting via MCP server.

This module handles posting markdown comments to JIRA tickets
using the JIRA MCP server.
"""

from dataclasses import dataclass


@dataclass
class JIRAComment:
    """
    Represents a comment to be posted to JIRA.

    Attributes:
        ticket_key: JIRA ticket identifier
        body: Comment content (markdown formatted)
        comment_id: JIRA comment ID (set after successful post)
    """
    ticket_key: str
    body: str
    comment_id: str | None = None

    def __post_init__(self):
        """Validate comment data."""
        if not self.body:
            raise ValueError("Comment body must not be empty")


def post_comment_to_jira(
    comment: JIRAComment,
    jira_url: str,
    verbose: bool = False
) -> str:
    """
    Post a comment to a JIRA ticket via MCP server.

    Args:
        comment: JIRAComment object to post
        jira_url: JIRA instance URL
        verbose: Enable verbose logging

    Returns:
        Comment ID from JIRA

    Raises:
        RuntimeError: If MCP server interaction fails
        PermissionError: If user lacks comment permission
        FileNotFoundError: If ticket doesn't exist

    Note:
        This function will use MCP tools to interact with JIRA.
        Implementation requires MCP server integration.
    """
    # TODO: Implement MCP server interaction
    # This requires using MCP tools which are not directly accessible in this context
    # The actual implementation will use the JIRA MCP server's jira_add_comment tool

    if verbose:
        import sys
        print(f"[DEBUG] Posting comment to {comment.ticket_key}", file=sys.stderr)

    raise NotImplementedError(
        "MCP server integration pending. "
        "This function requires JIRA MCP server tools for implementation."
    )
