#!/usr/bin/env python3
# Generated by Claude Code

"""Parse Slack thread URL and extract components."""

import re
import sys

def parse_slack_url(url: str) -> dict:
    """Extract channel_id and timestamp from Slack thread URL.

    Args:
        url: Slack thread URL (e.g., https://workspace.slack.com/archives/CHANNEL_ID/pTIMESTAMP)

    Returns:
        dict with 'channel_id' and 'thread_ts' keys

    Raises:
        ValueError: If URL format is invalid
    """
    pattern = r'https://[^/]+\.slack\.com/archives/([A-Z0-9]+)/p(\d+)'
    match = re.match(pattern, url)

    if not match:
        raise ValueError(
            "Invalid Slack thread URL format. "
            "Expected: https://workspace.slack.com/archives/CHANNEL_ID/pTIMESTAMP"
        )

    channel_id = match.group(1)
    timestamp_raw = match.group(2)

    # Convert pTIMESTAMP to TIMESTAMP.MICROSECONDS
    # e.g., p1769333522823869 → 1769333522.823869
    if len(timestamp_raw) < 6:
        raise ValueError(f"Invalid timestamp format: p{timestamp_raw}")

    thread_ts = f"{timestamp_raw[:-6]}.{timestamp_raw[-6:]}"

    return {
        'channel_id': channel_id,
        'thread_ts': thread_ts
    }

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: slack_thread_processor.py <slack-thread-url>", file=sys.stderr)
        sys.exit(1)

    try:
        result = parse_slack_url(sys.argv[1])
        print(f"{result['channel_id']}:{result['thread_ts']}")
    except ValueError as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
