#!/usr/bin/env -S uv run --script
# Generated by Claude Code
# /// script
# dependencies = []
# ///
"""
Upload Slack Thread to JIRA Ticket

This script exports a Slack thread conversation as a formatted markdown comment
to a JIRA ticket. It uses Slack MCP server for fetching messages and JIRA MCP
server for posting comments.

Usage:
    upload_slack_thread.py <slack_thread_url> [ticket_key] [--summary] [--verbose]

Examples:
    # With explicit ticket key
    upload_slack_thread.py "https://workspace.slack.com/archives/C123/p456" JN-1234

    # Auto-detect ticket from thread
    upload_slack_thread.py "https://workspace.slack.com/archives/C123/p456"

    # With AI summary
    upload_slack_thread.py "https://workspace.slack.com/archives/C123/p456" JN-1234 --summary
"""

import argparse
import os
import sys
from dataclasses import dataclass


# Exit codes per cli-interface.md
EXIT_SUCCESS = 0
EXIT_INVALID_ARGS = 1
EXIT_SLACK_ERROR = 2
EXIT_JIRA_ERROR = 3
EXIT_AUTH_ERROR = 4
EXIT_NOT_FOUND = 5


def parse_arguments() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description="Export Slack thread to JIRA ticket as markdown comment",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s "https://workspace.slack.com/archives/C123/p456" JN-1234
  %(prog)s "https://workspace.slack.com/archives/C123/p456" --summary
  %(prog)s "https://workspace.slack.com/archives/C123/p456" JN-1234 -v
        """
    )

    parser.add_argument(
        "slack_thread_url",
        help="Slack thread URL (format: https://workspace.slack.com/archives/CHANNEL_ID/pTIMESTAMP)"
    )

    parser.add_argument(
        "ticket_key",
        nargs="?",
        default=None,
        help="JIRA ticket key (format: PROJECT-NUMBER, e.g., JN-1234). Auto-detected if not provided."
    )

    parser.add_argument(
        "-s", "--summary",
        action="store_true",
        help="Enable AI-generated thread summary (default: disabled)"
    )

    parser.add_argument(
        "-v", "--verbose",
        action="store_true",
        help="Enable verbose logging for debugging"
    )

    return parser.parse_args()


def load_environment() -> tuple[str, str]:
    """
    Load required environment variables.

    Returns:
        Tuple of (jira_project_url, jira_api_token)

    Raises:
        SystemExit: If required environment variables are missing
    """
    jira_url = os.getenv("JIRA_PROJECT_URL")
    jira_token = os.getenv("JIRA_API_TOKEN")

    if not jira_url:
        print("ERROR: JIRA_PROJECT_URL environment variable not set", file=sys.stderr)
        print("\nPlease set the required environment variable:", file=sys.stderr)
        print("  export JIRA_PROJECT_URL='https://yourinstance.atlassian.net/'", file=sys.stderr)
        sys.exit(EXIT_INVALID_ARGS)

    if not jira_token:
        print("ERROR: JIRA_API_TOKEN environment variable not set", file=sys.stderr)
        print("\nPlease set the required environment variable:", file=sys.stderr)
        print("  export JIRA_API_TOKEN='your-api-token'", file=sys.stderr)
        sys.exit(EXIT_AUTH_ERROR)

    return jira_url, jira_token


def main() -> None:
    """Main entry point for the script."""
    args = parse_arguments()

    if args.verbose:
        print(f"[DEBUG] Slack thread URL: {args.slack_thread_url}", file=sys.stderr)
        print(f"[DEBUG] Ticket key: {args.ticket_key or '(auto-detect)'}", file=sys.stderr)
        print(f"[DEBUG] Summary enabled: {args.summary}", file=sys.stderr)

    # Load environment variables
    jira_url, jira_token = load_environment()

    if args.verbose:
        print(f"[DEBUG] JIRA URL: {jira_url}", file=sys.stderr)
        print("[DEBUG] JIRA API token loaded", file=sys.stderr)

    # TODO: Implementation will be added in subsequent tasks
    print("Implementation in progress...", file=sys.stderr)
    sys.exit(EXIT_SUCCESS)


if __name__ == "__main__":
    main()
