# Generated by Claude Code
"""
Slack Thread URL parsing and validation.

This module handles parsing and validation of Slack thread URLs,
extracting channel IDs and timestamps.
"""

import re
from dataclasses import dataclass


class InvalidURLError(ValueError):
    """Raised when a Slack thread URL is invalid."""
    pass


@dataclass
class SlackThreadURL:
    """
    Represents a parsed and validated Slack thread URL.

    Attributes:
        raw_url: Original URL provided by user
        workspace: Slack workspace identifier
        channel_id: Channel ID (e.g., "C09Q8MD1V0Q")
        thread_ts: Thread timestamp in decimal format (e.g., "1769333522.823869")
    """
    raw_url: str
    workspace: str
    channel_id: str
    thread_ts: str

    def __post_init__(self):
        """Validate all fields after initialization."""
        # Validate channel_id format
        if not re.match(r'^[A-Z0-9]+$', self.channel_id):
            raise InvalidURLError(
                f"Invalid channel ID format: {self.channel_id}\n"
                f"Expected: Uppercase letters and numbers only (e.g., C09Q8MD1V0Q)"
            )

        # Validate thread_ts is decimal format
        if not re.match(r'^\d+\.\d+$', self.thread_ts):
            raise InvalidURLError(
                f"Invalid thread timestamp format: {self.thread_ts}\n"
                f"Expected: Decimal format (e.g., 1769333522.823869)"
            )


def parse_slack_url(url: str) -> SlackThreadURL:
    """
    Parse and validate a Slack thread URL.

    Args:
        url: Slack thread URL to parse

    Returns:
        SlackThreadURL object with extracted components

    Raises:
        InvalidURLError: If URL format is invalid

    Example:
        >>> url = "https://redhat-internal.slack.com/archives/C09Q8MD1V0Q/p1769333522823869"
        >>> parsed = parse_slack_url(url)
        >>> parsed.channel_id
        'C09Q8MD1V0Q'
        >>> parsed.thread_ts
        '1769333522.823869'
    """
    # Pattern: https://<workspace>.slack.com/archives/<CHANNEL_ID>/p<TIMESTAMP>
    pattern = r'https://([^/]+)\.slack\.com/archives/([A-Z0-9]+)/p(\d+)'
    match = re.match(pattern, url)

    if not match:
        raise InvalidURLError(
            f"Invalid Slack thread URL format: {url}\n"
            f"Expected format: https://workspace.slack.com/archives/CHANNEL_ID/pTIMESTAMP\n"
            f"Example: https://redhat-internal.slack.com/archives/C09Q8MD1V0Q/p1769333522823869"
        )

    workspace = match.group(1)
    channel_id = match.group(2)
    timestamp_str = match.group(3)

    # Convert p format timestamp to decimal format
    # p1769333522823869 -> 1769333522.823869
    if len(timestamp_str) < 10:
        raise InvalidURLError(
            f"Invalid timestamp format: p{timestamp_str}\n"
            f"Timestamp too short"
        )

    # Insert decimal point before last 6 digits
    thread_ts = f"{timestamp_str[:-6]}.{timestamp_str[-6:]}"

    return SlackThreadURL(
        raw_url=url,
        workspace=workspace,
        channel_id=channel_id,
        thread_ts=thread_ts
    )
